name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        run: |
          curl -sSL "https://cs2mousetracker-dd6zri2zn7hatssysq28q5.streamlit.app/" -o /dev/null -w "HTTP Status: %{http_code}\n"
